---
spring:
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false
  web:
    resources:
      add-mappings: false
  cache:
    ehcache:
      config: classpath:ehcache.xml
  profiles:
    group:
      local: "local-envs,local-db"
      dev: ""
      production: ""
    active: local
  security:
    user:
      password: 'ACDF62BAB5119'
---
# local env
spring.config.activate.on-profile: local-envs

---
# local db
spring.config.activate.on-profile: local-db

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://localhost:3306/MY_CRYPTO?useUnicode=yes&characterEncoding=UTF-8"
    username: "root"
    password: "nextage2020!"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false